### ISSUE TITLE
[CRITICAL] [GENOCIDAL] [OVER 9000 KILLED] Shuttle disassembles and reassembles causing death of those on it

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStation/HippieStation13#123] opened 2017-02-10 02:55 UTC
As soon as the shuttle launches, it de-assembles into space, if you are in the right spot and unlucky enough, you actually get spaced as soon as the shuttle launches. Happened to me this round. I was a Captain, shuttle launched while I was in the shuttle brig, and then I immediately got spaced as I see the shuttle decompose line by line into space tiles in a matter of seconds.

Seems like a critical bug.

**Comment by Sarcalogo** [comment] 2017-02-10 06:45
Also causes the whole shuttle to become airless.

**Comment by yobob591** [comment] 2017-02-10 21:13
thats not a bug, thats how shuttles work in the new system. Its supposed to happen fast enought that its unnoticeable but lag can cause weird shit to go down and do what you were talking about

**Comment by Sarcalogo** [comment] 2017-02-10 22:12
Sounds like a retarded as fuck system because it leaves the shuttle airless 100% of the time.

**Comment by yobob591** [comment] 2017-02-10 22:30
I just witnessed this kill 4 people, high priority

**Comment by Jsau7** [comment] 2017-02-11 01:12
It keeps happening to me

**Comment by yobob591** [comment] 2017-02-11 03:10
This is a really gay bug that happens almost every round to at least 2 people

**Comment by jediluke1999** [comment] 2017-02-11 03:15
Kill me too, fair enough. I think resting fixes it, as well as sitting in a chair. But this really needs a true fix.

**Comment by Spacedong** [comment] 2017-02-11 04:19
lmao someone add those titles as actual labels

**Comment by JamieH** [comment] 2017-02-11 15:55
This should be fixed now.

**Comment by JamieH** [comment] 2017-02-11 16:25
The air is fixed, but this is still an issue.

**Closed** 2017-02-11 19:32 UTC
